### PR TITLE
Update note-collapsed.less

### PR DESCRIPTION
**Pull request by alastairjardine**
Giving the collapsed notes a bit more height because…nice.

Needs testing at all the different screen sizes & font preference sizes etc.

### CODE REVIEW

**Comment by hmgibson23** [comment]
:+1: Now the challenge will be to do a release!

**Comment by alastairjardine** [comment]
trolling

**Comment by robinedman** [comment]
@alastairjardine It's the automatic tests not running. Currently you have to jump through...
jumping-through-hoops

... to be able to run them successfully.

**HOWEVER**, this is a simple style change so I wouldn't worry about it. You may press the red button.

**Comment by robinedman** [comment]
:+1:

**Comment by alastairjardine** [comment]
@robinedman Scared

**Pull request merged**
