### PR TITLE
Jscs style guide

### PR DESCRIPTION
**Pull request by AleLudovici**
This PR adds a JSCS configuration file with a set of validation rules that define our code style guide.
You can [run JSCS](http://jscs.info/overview.html) by command line or use it through a linter plugin which depends from the text editor/IDE in use.

**TEST**
Unit tests should pass as usual but there's nothing to test in particular. To check whether JSCS its working in your local environment you should break one of the rules in a .js file and run JSCS against that file. Then JSCS should output this error.

### CODE REVIEW

**Comment by theefer** [comment]
Lovely, I want one of those for the Grid :-) /cc @jamesgorrie

**Comment by cutandpastey** [comment]
Yeah jscs is pretty awesome.  Maybe @AleLudovici should put the `.jscsrc` in a gist and pass it around?  That way we could have a decent style guide for the department?

**Comment by AleLudovici** [comment]
@cutandpastey Yes, it could be useful but does the department need/want to have a common style guide? Or it's just it's teams that define their own?

**Comment by cutandpastey** [comment]
I think if theres going to be more movement between streams it would be useful.  But, you know, you can always not include it in your project.

**Comment by theefer** [comment]
I'm happy to copy paste it from here (and adapt if necessary) to be honest...

**Comment by cutandpastey** [comment]
:+1:

**Pull request merged**
