### PR TITLE
Configurable tags

### PR DESCRIPTION
**Pull request by cutandpastey**
This PR adds the ability to construct notes of different tags i.e `<gu-flag></gu-flag>`.

### QA
Test all note functionality on the example page using F9, ensure `gu-flag` tags are constructed.

### CODE REVIEW

**Comment by robinedman** [comment]
Is this supposed to be a first step or a more complete "flag & correct" thing? Would help to know when reviewing it. If it's literally what the description says it looks good to me :) but otherwise I can immediately see some issues!

Such as:

- This includes "flag" but not "correct".
- You're able to create notes within flags (and the other way around), which seems a bit odd.

**Comment by cutandpastey** [comment]
Iv'e added tests and fixes for note collision, so if @robinedman is happy can we merge?

**Comment by robinedman** [comment]
It's still possible to create a note within a flag and vice versa so I'm not sure if the collision stuff is working.

A couple of more things:

- If you create a note and a flag next to each other, then you can't put the cursor between them.
- If you flag some text, then unflag a part of it, then note the whole thing you'll end up with flags and notes next to each other (probably "correct" in terms of the current merging behaviour but maybe disallow things like this?)

**Comment by cutandpastey** [comment]
@robinedman note collision should now be fixed.

**Comment by robinedman** [comment]
Can't test this atm. The build fix broke the build (https://github.com/guardian/scribe-plugin-noting/commit/10489c556148864a8ae071ab2b470dd6451cac36).

Now `npm run build` doesn't build the JS anymore for some reason.

**Comment by cutandpastey** [comment]
Fixed

**Comment by robinedman** [comment]
Works really well now! :+1:

**Comment by cutandpastey** [comment]
Cool, I'll wait for travis before releasing.

**Comment by cutandpastey** [comment]
Im reverting this to get the fix for https://github.com/guardian/scribe-plugin-noting/issues/75 out

**Pull request merged**
