### PR TITLE
Selecting a whole note using double click / cmd-shift-a

### PR DESCRIPTION
**Pull request by cutandpastey**
Added the ability to select a whole note as discussed here: https://github.com/guardian/scribe-plugin-noting/issues/81 you can do this by double clicking a note or by pressing `cmd-shift-a` whilst inside of a note.

### CODE REVIEW

**Comment by cutandpastey** [comment]
@alastairjardine needs to confirm he's okay with the key combo.

**Comment by hmgibson23** [comment]
Is your js magic formatter working?

**Comment by hmgibson23** [comment]
Looks fine apart from the formatting :+1:

**Comment by theefer** [comment]
Presumably double clicking outside of a note should still behave as normal (selects the word)? Could a test be added to assert this behaviour?

**Comment by cutandpastey** [comment]
Yeah https://github.com/guardian/scribe-plugin-noting/pull/89/files#diff-652760a3da976bf994551279fce031afR124 ensures that a selection MUST be totally within a note of a given tag-name before anything happens.

**Comment by theefer** [comment]
But won't you have [`preventedDefault()`](https://github.com/guardian/scribe-plugin-noting/pull/89/files#diff-652760a3da976bf994551279fce031afR94) before that?

**Comment by cutandpastey** [comment]
`preventDefault()` seems to have no effect on selections.  This is why I moved the interaction to a double click. The original intention was to use a triple click, but as this selects the whole paragraph (which can't be canceled without removing ranges) you can't drop any markers and is therefore useless.

**Comment by theefer** [comment]
Cool, all good then!

**Pull request closed without merging**
